### ISSUE TITLE
Newtonsoft.Json requirement

### ISSUE THREAD

**Issue by sixlettervariables** [SteeltoeOSS/CircuitBreaker#1]
Could the JSON serialization be abstracted out of Core? We are migrating away from Newtonsoft.Json, and I noticed this project has a hard reference to it.

**Comment by TimHess** [comment]
@sixlettervariables I don't think we're married to Newtonsoft, but removing the dependency is not currently a priority for us and it looks like its playing a pretty important role in this library right now. What are you using instead of Newtonsoft?

**Comment by sixlettervariables** [comment]
We're adopting JSON Schema and are going with Manatee.Json, as Newtonsoft's schema offering is paid. The trouble we're having is how deep the dependency seems to go!

**Comment by dtillman** [comment]
@sixlettervariables 
The depth of usage of Newtonsoft.Json in Hystrix is for serializing metrics/status to the dashboard.  

It gets used if you are trying to capture command metrics/status and send it to the dashboard.  This would mean in your app you reference and use Steeltoe.CircuitBreaker.Hystrix.MetricsEventsCore,  Steeltoe.CircuitBreaker.Hystrix.MetricsStreamCore or  Steeltoe.CircuitBreaker.Hystrix.MetricsStreamAutofac ... 

Dave

**Comment by dtillman** [comment]
Any more questions feel free to reach out to us.
