### ISSUE TITLE
HystrixCommand Interface methods

### ISSUE THREAD

**Issue by s4kas** [SteeltoeOSS/CircuitBreaker#10]
Hi, is it possible to pass parameters to the Run or RunFallback methods (and their async variations)?

Thanks :smiley:

**Comment by TimHess** [comment]
Hi @s4kas,

Not directly, but you can create some additional methods with parameters that then call ExecuteAsync - have a look at the Music Store sample for some ideas https://github.com/SteeltoeOSS/Samples/tree/dev/MusicStore/src/MusicStoreUI/Services/HystrixCommands

**Comment by dtillman** [comment]
Hi @s4kas: 
If you need any more help feel free to reach out on slack or open up another issue.
Dave
