### ISSUE TITLE
Question about HystrixCommand

### ISSUE THREAD

**Issue by catcherwong** [SteeltoeOSS/CircuitBreaker#11]
Hello!

Should we must create a new Command class like [FortuneServiceCommand](
https://github.com/SteeltoeOSS/Samples/blob/dev/CircuitBreaker/src/AspDotNetCore/FortuneTeller/Fortune-Teller-UI/Services/FortuneServiceCommand.cs) and add it to the dependency injection container in Startup class?

Is there any way to use circuit breaker with Attribute? 

For example,

```cs
[HystrixCommand(FallbackMethod = "RunRandomFortuneFallbackAsync")]
public async Task<Fortune> RandomFortuneAsync()
{
    var client = GetClient();
    var result = await client.GetStringAsync(RANDOM_FORTUNE_URL); 
    _logger.LogInformation("RandomFortuneAsync: {0}", result);

    return JsonConvert.DeserializeObject<Fortune>(result);
}

//fallback method
public async Task<Fortune> RunRandomFortuneFallbackAsync()
{
    _logger.LogInformation("RunFallback");
    return await Task.FromResult<Fortune>(new Fortune() { Id = 9999, Text = "You will have a happy day!" });
}
```
Maybe the above code is more convenient to use.

**Comment by TimHess** [comment]
Hi @catcherwong,

That could be a neat way to do it, but we do not currently have support for HystrixCommand via Attribute.

Another way of working with outbound http requests would be with DelegatingHandlers in HttpClientFactory. We experimented with the idea a bit several weeks ago, but have not yet come to a resolution on an ideal path forward - you can look at these branches in the samples repo for ideas about where we are thinking about going https://github.com/SteeltoeOSS/Samples/tree/hystrix-HttpClientFactory and https://github.com/SteeltoeOSS/Samples/tree/hystrix-factory-dave-ideas

**Comment by catcherwong** [comment]
@TimHess 

Thanks for your answer!  Those ideas are vary good! And I will have a try for this.

**Comment by dtillman** [comment]
Any more questions feel free to reach out to us
