### ISSUE TITLE
HystrixCommand that needs to call async functions

### ISSUE THREAD

**Issue by bloritsch** [SteeltoeOSS/CircuitBreaker#14]
I'm writing the C# equivalent to NetFlix Feign ([Dhaven.Faux](https://github.com/bloritsch/DHaven.Faux)), which is already using Discovery support.  I'm in the process of writing the class generators for Hystrix support as well.  The problem I'm facing is setting up the generic HystrixCommand so that I can handle `async` interfaces as well as synchronous ones.  What I would love to do is something like this:

        public async Task<string> Upload(Stream content, string mimeType, long length, string disposition)
        {
            var options = new HystrixCommandOptions(groupKey, HystrixCommandKeyDefault.AsKey(nameof(Upload)));

            var command = new HystrixCommand<string>(options, async () =>
            {
                var 仮variables = new System.Collections.Generic.Dictionary<string, object>();
                var 仮reqParams = new System.Collections.Generic.Dictionary<string, string>();
                var 仮request = CreateRequest(System.Net.Http.HttpMethod.Post, "/", 仮variables, 仮reqParams);
                var 仮content = StreamRawContent(content);
                仮content.Headers.Add("Content-Type", mimeType?.ToString());
                仮content.Headers.Add("Content-Length", length.ToString());
                仮content.Headers.Add("Content-Disposition", disposition?.ToString());
                仮request.Content = 仮content;
                var 仮response = await InvokeAsync(仮request);
                return GetHeaderValue<string>(仮response, "ETag");
            },
            async () => await fallback.Upload(content, mimeType, length, disposition), logger);

            return await command.ExecuteAsync();
        }

However that doesn't compile because `async` lambdas return `Task<T>` rather than `Func<T>`.  My underlying method that actually invokes the external web service is asynchronous mainly because the core `HttpClient` code is also asynchronous.  While I do have a synchronous variation, it's at the cost of explicitly awating the results from the asynchronous call.  (won't work in a single core VM).

What are my options in this case?  This is just one example generated method in a class with multiple generated methods.

**Comment by bloritsch** [comment]
It would be nice, but due to other requirements I have a workaround where I generate the commands themselves.

**Comment by jkonicki** [comment]
@dtillman Did you want to look at this change? They found a workaround, but might be worth looking to see if there is a better solution.
