### ISSUE TITLE
HdrHistogram  using too much memory

### ISSUE THREAD

**Issue by Lightgogogo** [SteeltoeOSS/CircuitBreaker#18]
My Appliaction services use CircuitBreaker to communicate with background services. But I found that every time I Instantiate a different HystrixCommand, it consumed tens of mb of memory.I have hundreds of  HystrixCommand in my Appliaction. I think it will cause the "out of memory" problem. How can't I Avoid this situation?

**Comment by Lightgogogo** [comment]
![qq 20181219091203](https://user-images.githubusercontent.com/37182806/50192737-7bcf9b80-036e-11e9-924d-4b4c3c8142eb.png)

**Comment by dtillman** [comment]
@Lightgogogo : Thanks for reporting .. we fixed this in 2.2 of Steeltoe
