### ISSUE TITLE
Steeltoe circuit breaker CircuitBreakerSleepWindowInMilliseconds property issue

### ISSUE THREAD

**Issue by karthikrajakandasamy** [SteeltoeOSS/CircuitBreaker#8]
In steeltoe circuit breaker i set the CircuitBreakerRequestVolumeThreshold as 5 and CircuitBreakerSleepWindowInMilliseconds as 2 mins. After 5 failure request the window should go to sleep mode for 2 mins(as per the circuit breaker logic), but for me it is going 4 minutes sleep mode which means doubled from my configuration value which i set. Do i need to change any other property. Can anyone please provide the solution. Thanks in advance

**Comment by dtillman** [comment]
@karthikrajakandasamy 
1. Are you running on .NET Core or .NET Full framework ?
2. Are you running on Windows, Linux or Mac?
Dave

**Comment by dtillman** [comment]
@karthikrajakandasamy 
Reach out again if you are still having issues
