### ISSUE TITLE
In SteelToe circuit Breaker we dont found any Half open state

### ISSUE THREAD

**Issue by karthikrajakandasamy** [SteeltoeOSS/CircuitBreaker#9]
We took the steel toe circuit breaker code in our local, where we dont find any half-open status, all we got is open state only. Can anyone give me suggestion for this

**Comment by dtillman** [comment]
@karthikrajakandasamy 
What do mean by "half open state"?
Davve

**Comment by dtillman** [comment]
If you are still having problems, let us know!
